---
- hosts: chirpr
  become: yes
  become_method: sudo
  tasks:
    - name: Update cache
      apt: update_cache=yes
    - name: Install items
      apt: name={{ item }} state=latest
      with_items:
        - git
        - nginx
        - python-pip
        - python-dev
    - name: clone project
      git:
        repo: git://github.com/puravshah7495/Chirpr.git
        dest: /home/notdecaf/Chirpr
        update: yes
        version: master
        depth: 1
    - name: curl node
      shell: 'curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -'
    - name: Install nodejs
      apt: name={{ item }} state=present
      with_items:
        - nodejs
        - build-essential 
    - name: Install Node Packages
      npm:
        path: /notdecaf/Chirpr